### ISSUE TITLE
Export Image Files

### ISSUE THREAD

**Issue by Ke2Lz** [Mango-Heroes/rarity-catalog#1]
Exported all the individual traits from the rarity catalog and uploaded to Gitub

Rarity Catalog Hours
Exporting image files from rarity catalog

Monday: 8pm-11pm (3 hours)
Tuesday: 8pm-11:30pm (3.5 hours)

**Comment by etsploit** [comment]
@Ke2Lz @ me next time

**Comment by etsploit** [comment]
Paid. Project closed.
